### ISSUE TITLE
Does Not Open App, java.lang.NoClassDefFoundError: Failed resolution of: [Lkotlin/reflect/KProperty;

### ISSUE THREAD

**Issue by mihodihasan** [Tunous/SwipeActionView#20]
After integrating this library, app is not opening, bellow is logcat logs
`2019-09-16 10:21:01.666 5058-5058/ml.obhai.contractor.swipeviewtoaction E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ml.obhai.contractor.swipeviewtoaction, PID: 5058
    java.lang.NoClassDefFoundError: Failed resolution of: [Lkotlin/reflect/KProperty;
        at me.thanel.swipeactionview.SwipeActionView.<clinit>(Unknown Source:1)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at ml.obhai.contractor.swipeviewtoaction.MainActivity.onCreate(MainActivity.java:17)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.reflect.KProperty" on path: DexPathList[[zip file "/data/app/ml.obhai.contractor.swipeviewtoaction-cL5XnEccKCXJKPr-74C_ZQ==/base.apk"],nativeLibraryDirectories=[/data/app/ml.obhai.contractor.swipeviewtoaction-cL5XnEccKCXJKPr-74C_ZQ==/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at me.thanel.swipeactionview.SwipeActionView.<clinit>(Unknown Source:1) 
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:854) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
        at ml.obhai.contractor.swipeviewtoaction.MainActivity.onCreate(MainActivity.java:17) 
        at android.app.Activity.performCreate(Activity.java:7802) 
        at android.app.Activity.performCreate(Activity.java:7791) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) `

**Comment by dec04** [comment]
same problem

**Comment by Tunous** [comment]
> same problem

@dec04 Are you able to share minimal sample code that reproduces this problem?

**Comment by dec04** [comment]
> > same problem
> 
> @dec04 Are you able to share minimal sample code that reproduces this problem?

Oh, thank you for the not-too-long answer. But I already solved my problem by updating kotlin "dependencies". 

I use your code with pleasure. <3 Thanks

**Comment by Tunous** [comment]
Ok, that’s interesting. I wonder what is the real cause of that. I must say that I somehow missed this issue when original poster created it and didn’t reply here previously.

Are you able to give us a bit more details about how you updated the Kotlin “dependencies” so other people will be able to resolve the issue quicker in the future?

**Comment by dec04** [comment]
I just add  in built.gradle (projectname):

`buildscript {
    // Kotlin plugin need to work fucking Tunous SAV
    ext.kotlin_version = '1.3.61'
    ...
    dependencies {
        ...

        // Kotlin plugin need to work Tunous SAV
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        ...
    }
}`

**Comment by dec04** [comment]
I just add code in builds.gradle (projectname):

```
buildscript {

    // Kotlin plugin need to work Tunous SAV
    ext.kotlin_version = '1.3.61'

    dependencies {
        //....

        // Kotlin plugin need to work Tunous SAV
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        //....
        maven { url 'https://jitpack.io' }
    }
}
```


And in build.gradle (app):


```
// Kotlin plugin need to work Tunous SAV
apply plugin: 'kotlin-android'

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    //....

    // Tunous Swipe Action View
    implementation 'com.github.Tunous:SwipeActionView:1.3.0'

    // Kotlin library need to work Tunous SAV
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"

    //.....
}
```

And it's work!
